trajectory_planner_node:
  ros__parameters:
    # Trajectory generation parameters
    prediction_horizon: 4.0          
    time_step: 0.2                   
    num_rollouts: 5                  
    max_lateral_offset: 2.5          
    
    # Vehicle constraints
    max_velocity: 15.0               
    max_acceleration: 2.0            
    max_deceleration: -4.0           
    max_curvature: 0.2               
    
    # Cost function weights
    obstacle_cost_weight: 1000.0     
    path_deviation_weight: 10.0      
    smoothness_weight: 1.0           
    comfort_weight: 5.0              
    
    # Safety parameters
    safety_margin: 0.001               
    collision_check_resolution: 0.3  
    
    # Frame IDs
    base_frame_id: "base_link"
    map_frame_id: "map"

        
    # Obstacle detection parameters (updated for tighter clustering)
    max_detection_range: 50.0        # meters
    min_obstacle_height: -1.0         # meters
    max_obstacle_height: 5.0          # meters
    cluster_tolerance: 1.0            # meters - reduced for tighter clusters
    min_points_per_cluster: 3         # minimum points per cluster